--liquibase formatted sql

--changeset iconset:001-create-icons-table
--comment: Create main icons table with hash partitioning (MODULUS 128) for collision-free HPSS

CREATE TABLE IF NOT EXISTS icons (
    icon_id BIGSERIAL,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    tags TEXT[],
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (icon_id)
) PARTITION BY HASH (icon_id);

COMMENT ON TABLE icons IS 'Main icons table with 128 hash partitions (C(128,6)=4.3B combinations) for HPSS algorithm';
COMMENT ON COLUMN icons.icon_id IS 'Primary key, used for hash distribution across 128 partitions';
COMMENT ON COLUMN icons.tags IS 'Array of tags for categorization and filtering';
COMMENT ON COLUMN icons.metadata IS 'Flexible JSONB field for additional icon properties';

--changeset iconset:001-create-partitions-batch1 splitStatements:false
--comment: Create partitions 0-31 (batch 1 of 4)

CREATE TABLE icons_p0 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 0);
CREATE TABLE icons_p1 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 1);
CREATE TABLE icons_p2 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 2);
CREATE TABLE icons_p3 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 3);
CREATE TABLE icons_p4 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 4);
CREATE TABLE icons_p5 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 5);
CREATE TABLE icons_p6 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 6);
CREATE TABLE icons_p7 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 7);
CREATE TABLE icons_p8 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 8);
CREATE TABLE icons_p9 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 9);
CREATE TABLE icons_p10 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 10);
CREATE TABLE icons_p11 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 11);
CREATE TABLE icons_p12 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 12);
CREATE TABLE icons_p13 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 13);
CREATE TABLE icons_p14 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 14);
CREATE TABLE icons_p15 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 15);
CREATE TABLE icons_p16 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 16);
CREATE TABLE icons_p17 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 17);
CREATE TABLE icons_p18 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 18);
CREATE TABLE icons_p19 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 19);
CREATE TABLE icons_p20 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 20);
CREATE TABLE icons_p21 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 21);
CREATE TABLE icons_p22 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 22);
CREATE TABLE icons_p23 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 23);
CREATE TABLE icons_p24 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 24);
CREATE TABLE icons_p25 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 25);
CREATE TABLE icons_p26 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 26);
CREATE TABLE icons_p27 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 27);
CREATE TABLE icons_p28 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 28);
CREATE TABLE icons_p29 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 29);
CREATE TABLE icons_p30 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 30);
CREATE TABLE icons_p31 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 31);

--changeset iconset:001-create-partitions-batch2 splitStatements:false
--comment: Create partitions 32-63 (batch 2 of 4)

CREATE TABLE icons_p32 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 32);
CREATE TABLE icons_p33 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 33);
CREATE TABLE icons_p34 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 34);
CREATE TABLE icons_p35 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 35);
CREATE TABLE icons_p36 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 36);
CREATE TABLE icons_p37 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 37);
CREATE TABLE icons_p38 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 38);
CREATE TABLE icons_p39 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 39);
CREATE TABLE icons_p40 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 40);
CREATE TABLE icons_p41 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 41);
CREATE TABLE icons_p42 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 42);
CREATE TABLE icons_p43 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 43);
CREATE TABLE icons_p44 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 44);
CREATE TABLE icons_p45 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 45);
CREATE TABLE icons_p46 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 46);
CREATE TABLE icons_p47 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 47);
CREATE TABLE icons_p48 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 48);
CREATE TABLE icons_p49 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 49);
CREATE TABLE icons_p50 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 50);
CREATE TABLE icons_p51 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 51);
CREATE TABLE icons_p52 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 52);
CREATE TABLE icons_p53 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 53);
CREATE TABLE icons_p54 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 54);
CREATE TABLE icons_p55 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 55);
CREATE TABLE icons_p56 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 56);
CREATE TABLE icons_p57 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 57);
CREATE TABLE icons_p58 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 58);
CREATE TABLE icons_p59 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 59);
CREATE TABLE icons_p60 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 60);
CREATE TABLE icons_p61 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 61);
CREATE TABLE icons_p62 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 62);
CREATE TABLE icons_p63 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 63);

--changeset iconset:001-create-partitions-batch3 splitStatements:false
--comment: Create partitions 64-95 (batch 3 of 4)

CREATE TABLE icons_p64 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 64);
CREATE TABLE icons_p65 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 65);
CREATE TABLE icons_p66 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 66);
CREATE TABLE icons_p67 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 67);
CREATE TABLE icons_p68 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 68);
CREATE TABLE icons_p69 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 69);
CREATE TABLE icons_p70 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 70);
CREATE TABLE icons_p71 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 71);
CREATE TABLE icons_p72 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 72);
CREATE TABLE icons_p73 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 73);
CREATE TABLE icons_p74 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 74);
CREATE TABLE icons_p75 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 75);
CREATE TABLE icons_p76 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 76);
CREATE TABLE icons_p77 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 77);
CREATE TABLE icons_p78 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 78);
CREATE TABLE icons_p79 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 79);
CREATE TABLE icons_p80 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 80);
CREATE TABLE icons_p81 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 81);
CREATE TABLE icons_p82 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 82);
CREATE TABLE icons_p83 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 83);
CREATE TABLE icons_p84 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 84);
CREATE TABLE icons_p85 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 85);
CREATE TABLE icons_p86 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 86);
CREATE TABLE icons_p87 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 87);
CREATE TABLE icons_p88 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 88);
CREATE TABLE icons_p89 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 89);
CREATE TABLE icons_p90 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 90);
CREATE TABLE icons_p91 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 91);
CREATE TABLE icons_p92 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 92);
CREATE TABLE icons_p93 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 93);
CREATE TABLE icons_p94 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 94);
CREATE TABLE icons_p95 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 95);

--changeset iconset:001-create-partitions-batch4 splitStatements:false
--comment: Create partitions 96-127 (batch 4 of 4)

CREATE TABLE icons_p96 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 96);
CREATE TABLE icons_p97 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 97);
CREATE TABLE icons_p98 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 98);
CREATE TABLE icons_p99 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 99);
CREATE TABLE icons_p100 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 100);
CREATE TABLE icons_p101 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 101);
CREATE TABLE icons_p102 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 102);
CREATE TABLE icons_p103 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 103);
CREATE TABLE icons_p104 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 104);
CREATE TABLE icons_p105 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 105);
CREATE TABLE icons_p106 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 106);
CREATE TABLE icons_p107 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 107);
CREATE TABLE icons_p108 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 108);
CREATE TABLE icons_p109 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 109);
CREATE TABLE icons_p110 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 110);
CREATE TABLE icons_p111 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 111);
CREATE TABLE icons_p112 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 112);
CREATE TABLE icons_p113 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 113);
CREATE TABLE icons_p114 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 114);
CREATE TABLE icons_p115 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 115);
CREATE TABLE icons_p116 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 116);
CREATE TABLE icons_p117 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 117);
CREATE TABLE icons_p118 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 118);
CREATE TABLE icons_p119 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 119);
CREATE TABLE icons_p120 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 120);
CREATE TABLE icons_p121 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 121);
CREATE TABLE icons_p122 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 122);
CREATE TABLE icons_p123 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 123);
CREATE TABLE icons_p124 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 124);
CREATE TABLE icons_p125 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 125);
CREATE TABLE icons_p126 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 126);
CREATE TABLE icons_p127 PARTITION OF icons FOR VALUES WITH (MODULUS 128, REMAINDER 127);

--changeset iconset:001-create-icon-sets-table
--comment: Create icon_sets table to store generated sets with metadata

CREATE TABLE IF NOT EXISTS icon_sets (
    id BIGSERIAL PRIMARY KEY,
    request_id UUID NOT NULL,
    set_index INT NOT NULL,
    icon_ids BIGINT[] NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    metadata JSONB,
    UNIQUE(request_id, set_index)
);

CREATE INDEX IF NOT EXISTS idx_icon_sets_request ON icon_sets(request_id);
CREATE INDEX IF NOT EXISTS idx_icon_sets_created ON icon_sets USING BRIN(created_at) WITH (pages_per_range = 128);

COMMENT ON TABLE icon_sets IS 'Stores generated icon sets with request tracking';
COMMENT ON COLUMN icon_sets.request_id IS 'UUID identifying the generation request (groups related sets)';
COMMENT ON COLUMN icon_sets.set_index IS 'Index of this set within the request (0-based)';
COMMENT ON COLUMN icon_sets.icon_ids IS 'Array of icon IDs in this set';

--rollback DROP TABLE IF EXISTS icon_sets CASCADE;
--rollback DROP TABLE IF EXISTS icons CASCADE;
